<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="IOpProvider.cs" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="appSettings.json" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="appSettings.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="HigginsSoft.DotMpi" Version="1.0.58" />
		<PackageReference Include="ManagedCuda-12" Version="12.1.51" />
		<PackageReference Include="ManagedCuda-CUBLAS" Version="12.1.51" />
		<PackageReference Include="ManagedCuda-NVRTC" Version="12.1.51" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="Microsoft.TestPlatform" Version="17.13.0" />
		<PackageReference Include="coverlet.collector" Version="3.1.2" />
		<PackageReference Include="MSTest" Version="3.8.2" />
	</ItemGroup>

	<ItemGroup>

		<ProjectReference Include="..\..\HigginsSoft.Math.Lib.Database\HigginsSoft.Math.Lib.Database.csproj" />

		<ProjectReference Include="..\..\src\HigginsSoft.Math.Demos\HigginsSoft.Math.Demos.csproj" />

		<ProjectReference Include="..\..\src\HigginsSoft.Math.Lib\HigginsSoft.Math.Lib.csproj" />
	</ItemGroup>

</Project>
